### PR TITLE
Updated on-prem install instructions

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by pgerv12 — COMMENTED** [review]
Looks good, one item I think we need to add (maybe not here, but in using) is that the Streams domain and instance are created and started. Thoughts?

**Comment by pgerv12** [comment]
Oh! Also, the self-signed certificate crap and steps to solve that :/ (QSE users won't have an issue I think)

**Comment by ghost** [comment]
Good idea, both.

The first is easy, the second I honestly don't remember and don't seem to have notes. Do you? If not I can recreate.

I haven't tried out the 4.3 QSE because I couldn't get the docker stuff to work on eden104, but why would there be no issue there? Isn't it a self-signed cert?

**Comment by pgerv12** [comment]
I don't have notes, I think you have to add it to key/trust store in java install using keytool or something? The QSE automatically performs this step.

**Comment by mrshenli** [comment]
Regarding the installation, the current description assumes that our runner toolkit is given to users as a tarball. I saw other existing toolkits in the Streams install is already in the extracted form. Is there any reason that we are different from others?

**Comment by ghost** [comment]
@mrshenli Not sure, though my guess would be that the tarball is there to be downloadable from the Console.

**Comment by mrshenli** [comment]
@pgerv12 do you know if our runner is included in the on-prem install or users have to download it from the console?

**Comment by pgerv12** [comment]
It is included in the on-prem install. It is located in `$STREAMS_INSTALL/etc/beam`. The runner can be downloaded from the console as well, but that requires that a user has started their Streams domain and the download just pulls from that `etc/beam` location anyway.

**Pull request merged**
